/** Central Serbian UI copy for shared product, catalog, media, and scanner flows. */
export const sr = {
  common: {
    cancel: 'Otkaži',
    retry: 'Pokušaj ponovo',
  },
  product: {
    addTitle: 'Dodaj novi proizvod',
    editTitle: 'Izmeni proizvod',
    addDescription: 'Dodajte proizvod u asortiman. Polja označena zvezdicom su obavezna.',
    editDescription: 'Izmenite podatke o proizvodu.',
    name: 'Naziv proizvoda',
    namePlaceholder: 'Unesite naziv proizvoda',
    skuPlaceholder: 'Unesite SKU ili skenirajte barkod',
    quantityTip: 'Skenirajte isti barkod više puta da automatski povećate količinu.',
    description: 'Opis',
    descriptionPlaceholder: 'Unesite opis proizvoda (opciono)',
    image: 'Slika proizvoda',
    imageDescription: 'Otpremite sliku proizvoda. Najveća veličina fajla je 5 MB.',
    create: 'Kreiraj proizvod',
    update: 'Sačuvaj izmene',
    invalidBarcode: 'Neispravan barkod',
    invalidBarcodeDescription: 'Skenirani barkod je prekratak ili neispravan. Pokušajte ponovo.',
    unknown: 'Nepoznat proizvod',
    notFound: 'Proizvod nije pronađen',
    notFoundDescription: 'Pretražene su dostupne baze. SKU je sačuvan; unesite podatke ručno.',
    lookupFailed: 'Podaci o proizvodu nisu učitani',
    lookupFailedDescription: 'Unesite podatke o proizvodu ručno.',
  },
  category: {
    label: 'Kategorija',
    select: 'Izaberite kategoriju',
    uncategorized: 'Bez kategorije',
    add: 'Dodaj novu kategoriju',
    createTitle: 'Kreiraj novu kategoriju',
    createDescription: 'Dodajte kategoriju za organizaciju proizvoda.',
    name: 'Naziv kategorije',
    namePlaceholder: 'npr. Čokolade, kafa, šamponi',
    description: 'Opis (opciono)',
    descriptionPlaceholder: 'Kratak opis kategorije',
    create: 'Kreiraj kategoriju',
    created: 'Kategorija je kreirana',
    createFailed: 'Kategorija nije kreirana',
    nameRequired: 'Naziv kategorije je obavezan',
  },
  image: {
    label: 'Slika',
    invalidFile: 'Neispravan fajl',
    selectImage: 'Izaberite fajl slike.',
    unsupportedFormat: 'Format nije podržan',
    unsupportedFormatDescription: 'HEIC nije podržan. Koristite JPG, PNG, WEBP ili GIF.',
    tooLarge: 'Fajl je prevelik',
    tooLargeDescription: 'Slika mora biti manja od 5 MB.',
    uploadFailed: 'Otpremanje nije uspelo',
    upload: 'Otpremi sliku',
    change: 'Promeni sliku',
    uploading: 'Otpremanje…',
    success: 'Slika je uspešno otpremljena',
    empty: 'Slika nije izabrana',
    preview: 'Pregled izabrane slike',
  },
  catalog: {
    client: 'Klijent',
    productCount: (count: number) => `${count} ${count === 1 ? 'proizvod' : 'proizvoda'}`,
    deleted: 'Katalog je obrisan',
    deletedDescription: 'Katalog je uklonjen iz evidencije.',
    deleteFailed: 'Katalog nije obrisan',
    tryAgain: 'Pokušajte ponovo.',
    confirmDelete: 'Da li sigurno želite da obrišete ovaj katalog?',
  },
  camera: {
    starting: 'Pokretanje kamere…',
    initializing: 'Priprema HD skenera i prepoznavanja barkoda…',
    retry: 'Pokušaj ponovo',
    flashlight: 'Uključi ili isključi blic',
    sound: 'Uključi ili isključi zvuk',
    zoom: 'Zum',
    zoomHelp: 'Podesite za teško čitljive ili zamućene kodove',
    cameraFallback: (index: number) => `Kamera ${index}`,
    flashlightFailed: 'Blic nije moguće uključiti ili isključiti',
    confirmed: 'Barkod je potvrđen',
    holdSteady: 'Držite kameru mirno',
    confirming: 'Potvrđivanje skeniranja…',
    startFailed: 'Skener nije moguće pokrenuti',
    unknownError: 'nepoznata greška',
    manualEntry: 'Unesi barkod ručno',
  },
} as const
