/** Central Serbian UI copy for shared product, catalog, media, and scanner flows. */
export const sr = {
  common: {
    cancel: 'Otkaži',
    retry: 'Pokušaj ponovo',
    signOut: 'Odjava',
    signingOut: 'Odjava…',
    home: 'Početna',
    dashboard: 'Početna tabla',
  },
  pdf: {
    download: 'Preuzmi PDF',
    generating: 'Priprema PDF-a…',
  },
  scan: {
    missingCostNote:
      'Brzi sken ne unosi nabavnu cenu. Dopunite je u asortimanu ili na Ulazu.',
  },
  route: {
    errorTitle: 'Nešto nije u redu',
    errorDescription: 'Stranica nije učitana. Pokušajte ponovo.',
    notFoundTitle: 'Stranica nije pronađena',
    notFoundDescription: 'Ova adresa ne postoji ili je uklonjena.',
    loading: 'Učitavanje…',
  },
  product: {
    addTitle: 'Dodaj novi proizvod',
    editTitle: 'Izmeni proizvod',
    addDescription: 'Dodajte proizvod u asortiman. Polja označena zvezdicom su obavezna.',
    editDescription: 'Izmenite podatke o proizvodu.',
    name: 'Naziv proizvoda',
    namePlaceholder: 'Unesite naziv proizvoda',
    nameEditableHint: 'Naziv iz skenirane baze je samo predlog — izmenite ga pre čuvanja ako je potrebno.',
    skuPlaceholder: 'Unesite SKU ili skenirajte barkod',
    quantityTip: 'Skenirajte isti barkod više puta da automatski povećate količinu.',
    salePrice: 'Cena',
    salePriceOptional: 'Cena (opciono)',
    salePriceDescription: 'Opciono. Možete je uneti sada ili kasnije na fakturi.',
    costPrice: 'Nabavna cena',
    costPriceDescription: 'Obavezna. Već je poznata pri ulazu robe i ne prikazuje se kupcu.',
    costPriceZeroReason: 'Razlog za nabavnu cenu 0',
    costPriceZeroReasonDescription:
      'npr. Promotivna roba, Besplatna zaliha dobavljača, Početni lager, Kompenzacija, Poklon/uzorak',
    description: 'Opis',
    descriptionPlaceholder: 'Unesite opis proizvoda (opciono)',
    image: 'Slika proizvoda',
    imageDescription: 'Otpremite sliku proizvoda. Najveća veličina fajla je 5 MB.',
    create: 'Kreiraj proizvod',
    update: 'Sačuvaj izmene',
    invalidBarcode: 'Neispravan barkod',
    invalidBarcodeDescription: 'Skenirani barkod je prekratak ili neispravan. Pokušajte ponovo.',
    unknown: 'Nepoznat proizvod',
    notFound: 'Proizvod nije pronađen',
    notFoundDescription: 'Pretražene su dostupne baze. SKU je sačuvan; unesite podatke ručno.',
    lookupFailed: 'Podaci o proizvodu nisu učitani',
    lookupFailedDescription: 'Unesite podatke o proizvodu ručno.',
  },
  finance: {
    missingCost: 'Nedostaje nabavna cena',
    missingCostDescription: (count: number) =>
      `${count} ${count === 1 ? 'plaćena faktura nema kompletne troškove' : 'plaćene fakture nemaju kompletne troškove'}.`,
  },
  category: {
    label: 'Kategorija',
    select: 'Izaberite kategoriju',
    uncategorized: 'Bez kategorije',
    add: 'Dodaj novu kategoriju',
    createTitle: 'Kreiraj novu kategoriju',
    createDescription: 'Dodajte kategoriju za organizaciju proizvoda.',
    name: 'Naziv kategorije',
    namePlaceholder: 'npr. Čokolade, kafa, šamponi',
    description: 'Opis (opciono)',
    descriptionPlaceholder: 'Kratak opis kategorije',
    create: 'Kreiraj kategoriju',
    created: 'Kategorija je kreirana',
    createFailed: 'Kategorija nije kreirana',
    nameRequired: 'Naziv kategorije je obavezan',
  },
  image: {
    label: 'Slika',
    invalidFile: 'Neispravan fajl',
    selectImage: 'Izaberite fajl slike.',
    unsupportedFormat: 'Format nije podržan',
    unsupportedFormatDescription: 'HEIC nije podržan. Koristite JPG, PNG, WEBP ili GIF.',
    tooLarge: 'Fajl je prevelik',
    tooLargeDescription: 'Slika mora biti manja od 5 MB.',
    uploadFailed: 'Otpremanje nije uspelo',
    upload: 'Otpremi sliku',
    change: 'Promeni sliku',
    uploading: 'Otpremanje…',
    success: 'Slika je uspešno otpremljena',
    empty: 'Slika nije izabrana',
    preview: 'Pregled izabrane slike',
    remove: 'Ukloni sliku',
    productPlaceholder: (name: string) => `Nema slike za proizvod ${name}`,
  },
  onboarding: {
    addProduct: 'Dodaj proizvod',
    companyMissing: 'Naziv firme i PIB se štampaju na fakturi.',
    openSettings: 'Popuni podatke firme',
    empty: {
      catalog: {
        title: 'Još nema kataloga',
        needProducts: 'Katalog se pravi od proizvoda iz asortimana. Prvo dodajte ili skenirajte proizvode.',
        ready: 'Izaberite proizvode, dodajte popust i pošaljite PDF kupcu.',
        createHref: '/catalogs/new',
        createLabel: 'Novi katalog',
      },
      invoice: {
        title: 'Još nema faktura',
        needProducts: 'Faktura se pravi od proizvoda iz asortimana. Prvo dodajte ili skenirajte proizvode.',
        ready: 'Izaberite proizvode iz asortimana i izdajte prvu fakturu kupcu.',
        createHref: '/invoices/new',
        createLabel: 'Nova faktura',
      },
    },
  },
  catalog: {
    newTitle: 'Novi katalog',
    newDescription: 'Kreirajte katalog od izabranih proizvoda i primenite popust.',
    emptyDescription: 'Prvo dodajte proizvode u asortiman.',
    goToInventory: 'Otvori asortiman',
    information: 'Podaci o katalogu',
    informationDescription: 'Unesite osnovne podatke za katalog.',
    name: 'Naziv kataloga',
    namePlaceholder: 'Unesite naziv kataloga',
    clientName: 'Naziv klijenta',
    clientNamePlaceholder: 'Unesite naziv klijenta (opciono)',
    backToList: 'Nazad na kataloge',
    backToCatalog: 'Nazad na katalog',
    editTitle: 'Izmena kataloga',
    editDescription: 'Izmenite podatke o katalogu i proizvode.',
    savedClient: 'Sačuvani kupac',
    savedClientPlaceholder: 'Izaberite kupca ili unesite ručno',
    saveClient: 'Sačuvaj kupca u listu',
    saveClientHelp: 'Biće dostupan i pri izradi faktura i narednih kataloga.',
    discount: 'Popust (%)',
    notes: 'Napomena',
    notesPlaceholder: 'Dodatna napomena (opciono)',
    selectProducts: 'Izaberite proizvode',
    selectProductsDescription: 'Izaberite najmanje jedan proizvod za katalog.',
    pricePreview: 'Pregled cena',
    pricePreviewDescription: (discount: number) => `Cene sa primenjenim popustom od ${discount}%`,
    create: 'Kreiraj katalog',
    update: 'Sačuvaj katalog',
    created: 'Katalog je kreiran',
    createdDescription: (name: string) => `Katalog „${name}“ je spreman.`,
    createFailed: 'Katalog nije kreiran',
    unexpectedError: 'Došlo je do neočekivane greške.',
    client: 'Klijent',
    productCount: (count: number) => `${count} ${count === 1 ? 'proizvod' : 'proizvoda'}`,
    deleted: 'Katalog je obrisan',
    deletedDescription: 'Katalog je uklonjen iz evidencije.',
    deleteFailed: 'Katalog nije obrisan',
    tryAgain: 'Pokušajte ponovo.',
    confirmDelete: 'Da li sigurno želite da obrišete ovaj katalog?',
    priceOnRequest: 'Cena na upit',
    display: 'Prikaz kataloga',
    displayDescription: 'Isti izgled važi za PDF i za javni link.',
    layout: 'Raspored',
    sortMode: 'Redosled proizvoda',
    groupByCategory: 'Grupiši po kategorijama',
    groupByCategoryHelp: 'Svaka kategorija dobija naslov i u PDF-u počinje na novoj strani. Duga kategorija nastavlja na narednim stranama, a sledeća kategorija počinje tek posle nje.',
    visibleFields: 'Prikaži na proizvodu',
    showSku: 'SKU / šifra',
    showDescription: 'Opis',
    showOriginalPrice: 'Stara cena (precrtana) kad postoji popust',
    manualOrder: 'Ručni redosled',
    manualOrderDescription: 'Strelicama pomerite proizvod gore ili dole.',
    moveUp: 'Pomeri gore',
    moveDown: 'Pomeri dole',
    searchPlaceholder: 'Pretraži proizvode…',
    allCategories: 'Sve',
    noResults: 'Nijedan proizvod ne odgovara pretrazi.',
  },
  camera: {
    starting: 'Pokretanje kamere…',
    initializing: 'Priprema HD skenera i prepoznavanja barkoda…',
    retry: 'Pokušaj ponovo',
    flashlight: 'Uključi ili isključi blic',
    sound: 'Uključi ili isključi zvuk',
    zoom: 'Zum',
    zoomHelp: 'Podesite za teško čitljive ili zamućene kodove',
    cameraFallback: (index: number) => `Kamera ${index}`,
    flashlightFailed: 'Blic nije moguće uključiti ili isključiti',
    confirmed: 'Barkod je potvrđen',
    holdSteady: 'Držite kameru mirno',
    confirming: 'Potvrđivanje skeniranja…',
    startFailed: 'Skener nije moguće pokrenuti',
    unknownError: 'nepoznata greška',
    manualEntry: 'Unesi barkod ručno',
  },
} as const
