import { defineConfig } from 'vitest/config'
import path from 'path'

export default defineConfig({
  test: {
    globals: false,
    environment: 'node',
    include: [
      'src/lib/intake-request.test.ts',
      'src/lib/scan-gate.test.ts',
      'src/lib/local-date.test.ts',
      'src/lib/invoice-totals.test.ts',
      'src/lib/invoice-vat.test.ts',
      'src/lib/invoice-validation.test.ts',
      'src/lib/invoice-status.test.ts',
      'src/lib/invoice-status-view.test.ts',
      'src/lib/landing-invoice-demo.test.ts',
      'src/lib/invoice-finance.test.ts',
      'src/lib/invoice-line.test.ts',
      'src/lib/product-picker.test.ts',
      'src/lib/invoice-stock.test.ts',
      'src/lib/api-error.test.ts',
      'src/lib/route-access.test.ts',
      'src/lib/stock-backfill.test.ts',
      'src/lib/stock-movement-query.test.ts',
      'src/lib/stock-movement-filters.test.ts',
      'src/lib/low-stock.test.ts',
      'src/lib/dashboard-activity.test.ts',
      'src/lib/draft-number.test.ts',
      'src/lib/persist-product-image.test.ts',
      'src/lib/server-storage.test.ts',
      'src/lib/safe-remote-url.test.ts',
      'src/lib/public-catalog.test.ts',
      'src/lib/product-validation.test.ts',
      'src/lib/barcode.test.ts',
      'src/lib/barcode-lookup.test.ts',
      'src/lib/authorized-fetch.test.ts',
      'src/lib/product-put.test.ts',
      'src/lib/purchase-price-rules.test.ts',
      'src/lib/profile-put.test.ts',
      'src/lib/image-src.test.ts',
      'src/lib/client-image-upload.test.ts',
      'src/lib/assortment-import.test.ts',
      'src/lib/camera-access.test.ts',
      'src/lib/invoice-number.test.ts',
      'src/lib/invoice-archive.test.ts',
      'src/lib/pwa-install.test.ts',
      'src/lib/rate-limit.test.ts',
      'src/lib/after-auth.test.ts',
      'src/lib/landing-copy.test.ts',
      'src/lib/catalog-layout.test.ts',
      'src/lib/catalog-picker.test.ts',
      'src/lib/unsaved-changes.test.ts',
      'src/lib/access-period.test.ts',
      'src/lib/access-guard.test.ts',
      'src/app/api/access-expired.test.ts',
      'src/lib/pdf-fonts.test.ts',
      'src/app/api/invoices/route.test.ts',
      'src/app/api/invoices/[id]/route.test.ts',
      'src/app/api/public/catalogs/[id]/route.test.ts',
      'src/app/api/uploads/route.test.ts',
      'src/app/api/profile/route.test.ts',
      'src/app/api/shared/catalog/[token]/route.test.ts',
      'src/app/api/shared/invoice/[token]/route.test.ts',
      'src/app/api/invoices/[id]/share/route.test.ts',
      'src/lib/public-invoice.test.ts',
      'src/lib/share-links.test.ts',
      'src/app/api/catalogs/[id]/route.test.ts',
      'src/app/api/stock-movements/route.test.ts',
      'src/app/api/products/bulk-adjust/route.test.ts',
      'src/app/api/products/fetch-by-barcode/route.test.ts',
      'src/app/api/categories/route.test.ts',
      'src/app/api/clients/route.test.ts',
      'src/lib/client-fill.test.ts',
      'src/lib/invoice-export.test.ts',
      'src/lib/ips-qr.test.ts',
      'src/lib/overdue-invoices.test.ts',
      'src/lib/analytics.test.ts',
      'src/lib/sentry-scrub.test.ts',
      'src/app/api/invoices/export/route.test.ts',
      'src/test/require-test-database.test.ts',
    ],
    exclude: [
      '**/node_modules/**',
      '**/*.db.test.ts',
      '**/*.integration.test.ts',
      '**/*.spec.ts',
      'e2e/**',
      'tests/**',
    ],
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
})
